import "./globals.css";
import { Roboto_Flex } from "next/font/google";

const roboto_Flex = Roboto_Flex({
  weight: "700",
  subsets: ["latin"],
});
export const metadata = {
  title: "Binladen",
  description: "scram words generated by oussama guenfoed (binladen)",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto_Flex.className}>{children}</body>
    </html>
  );
}
